### ISSUE TITLE
Deployments using Laravel Vapor try to write to a non-writable path

### ISSUE THREAD

**Issue by tomhatzer** [nWidart/laravel-modules#1049]
Hi there!

Last week we had the following exception fill our exception logging service:

```
Exception: The /var/task/bootstrap/cache directory must be present and writable.
#28 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(190): Illuminate\Foundation\ProviderRepository::writeManifest
#27 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(165): Illuminate\Foundation\ProviderRepository::compileManifest
#26 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository::load
#25 /vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Nwidart\Modules\Laravel\Module::registerProviders
#24 /vendor/nwidart/laravel-modules/src/Module.php(264): Nwidart\Modules\Module::register
#23 /vendor/nwidart/laravel-modules/src/FileRepository.php(321): Nwidart\Modules\FileRepository::register
#22 /vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(23): Nwidart\Modules\Providers\BootstrapServiceProvider::register
#21 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(627): Illuminate\Foundation\Application::register
#20 /vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(31): Nwidart\Modules\ModulesServiceProvider::registerModules
#19 /vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(17): Nwidart\Modules\LaravelModulesServiceProvider::boot
#18 [internal](0): call_user_func_array
#17 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#16 /vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\Util::unwrapIfClosure
#15 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\BoundMethod::callBoundMethod
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::call
#13 /vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\Container::call
#12 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\Foundation\Application::bootProvider
#11 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\Foundation\Application::Illuminate\Foundation\{closure}
#10 [internal](0): array_walk
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Foundation\Application::boot
#8 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Bootstrap\BootProviders::bootstrap
#7 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Application::bootstrapWith
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Console\Kernel::bootstrap
#5 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(261): Illuminate\Foundation\Console\Kernel::call
#4 /cliRuntime.php(45): {closure}
#3 /vendor/laravel/framework/src/Illuminate/Support/helpers.php(558): with
#2 /cliRuntime.php(46): require
#1 /runtime.php(30): require
#0 /opt/bootstrap.php(6): null
```

**Reason:** laravel-modules tries to store the module configuration files in a (for apps deployed with Laravel Vapor to AWS Lambda) non-writable directory.

**Solution:** This PR proposes a fix for the problem: https://github.com/nWidart/laravel-modules/pull/1048
The better solution here would be to use a system writable directory that's not laravel internal (like the one the package is using right now) that can be specified by using an ENV variable or likewise.

Have a great week!

Best wishes
Tom

**Comment by nWidart** [comment]
PR has been merged, thanks!
