### ISSUE TITLE
Error compiling module assets

### ISSUE THREAD

**Issue by 06tech** [nWidart/laravel-modules#1328]
Just started work with a Laravel project that is using Modules and I am trying to compile module assets with npm run dev and I get the errors reproduced below...

Any ideas?
Thanks!

```
ERROR  Failed to compile with 2 errors 
 error  in ./Resources/assets/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from PROJECT_ROOT_FOLDER/node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (PROJECT_ROOT_FOLDER/node_modules/sass-loader/dist/index.js:25:24)
    at PROJECT_ROOT_FOLDER/Modules/MODULE_NAME/node_modules/webpack/lib/NormalModule.js:316:20
    at PROJECT_ROOT_FOLDER/Modules/MODULE_NAME/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at PROJECT_ROOT_FOLDER/Modules/MODULE_NAME/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 error  in ./Resources/assets/sass/app.scss

Module build failed (from PROJECT_ROOT_FOLDER/node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (PROJECT_ROOT_FOLDERt/node_modules/sass-loader/dist/index.js:25:24)

 @ ./Resources/assets/sass/app.scss 2:14-277
```

**Comment by dcblogdev** [comment]
I've tried this on a new module in my case the CSS file is generated without any errors.

Try deleting the node_modules folder and run the command again.

**Comment by 06tech** [comment]
I just created a brand new module 'Reports':-

artisan module:make Reports

changed directory to the module root and ran:-

npm install

then

npm run dev

Same error - below is the debug output log file contents if that helps?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:PROJECT_ROOT_FOLDER/Modules/Reports/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/mysql/bin:/HOME_DIR/.composer/vendor/bin:/HOME_DIR:./:/usr/local/sbin
9 verbose lifecycle @~dev: CWD: PROJECT_ROOT_FOLDER/Modules/Reports
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 2  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd PROJECT_ROOT_FOLDER/Modules/Reports
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error @ dev: `npm run development`
22 error Exit status 2
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

Any other ideas?
Thanks
