### ISSUE TITLE
module:make command fails

### ISSUE THREAD

**Issue by ahlvd** [nWidart/laravel-modules#1457]
This just drives me crazy and I can't figure out why it does not work. What I want to do ist create a new module, which we have done before several times. But the command fails with a "ModuleNotFoundException" which is weired.

As you can see, some files are generated successfully, but when it comes to create the ServiceProvider it fails.

```
bash-5.1# artisan module:make Test

   INFO  Creating module: [Test].  

  Generating file modules/Test/module.json ................................................................................................ 4ms DONE
  Generating file modules/Test/routes/frontend.php ........................................................................................ 4ms DONE
  Generating file modules/Test/routes/backend.php ......................................................................................... 4ms DONE
  Generating file modules/Test/Config/config.php .......................................................................................... 6ms DONE
  Generating file modules/Test/Resources/js/app.js ....................................................................................... 14ms DONE
  Generating file modules/Test/webpack.mix.js ............................................................................................. 9ms DONE
[2022-09-02 12:57:40] local.ERROR: Module [Test] does not exist! {"exception":"[object] (Nwidart\\Modules\\Exceptions\\ModuleNotFoundException(code: 0): Module [Test] does not exist! at /var/www/traktorpool/vendor/nwidart/laravel-modules/src/FileRepository.php:366)
[stacktrace]
#0 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Traits/ModuleCommandTrait.php(16): Nwidart\\Modules\\FileRepository->findOrFail('Test')
#1 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Commands/ProviderMakeCommand.php(101): Nwidart\\Modules\\Commands\\ProviderMakeCommand->getModuleName()
#2 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Commands/GeneratorCommand.php(37): Nwidart\\Modules\\Commands\\ProviderMakeCommand->getDestinationFilePath()
#3 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Nwidart\\Modules\\Commands\\GeneratorCommand->handle()
#4 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\\Container\\Container->call(Array)
#9 /var/www/traktorpool/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#11 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(68): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#12 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('module:make-pro...', Array, Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Generators/ModuleGenerator.php(414): Illuminate\\Console\\Command->call('module:make-pro...', Array)
#14 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Generators/ModuleGenerator.php(334): Nwidart\\Modules\\Generators\\ModuleGenerator->generateResources()
#15 /var/www/traktorpool/vendor/nwidart/laravel-modules/src/Commands/ModuleMakeCommand.php(46): Nwidart\\Modules\\Generators\\ModuleGenerator->generate()
#16 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Nwidart\\Modules\\Commands\\ModuleMakeCommand->handle()
#17 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#19 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\\Container\\Container->call(Array)
#22 /var/www/traktorpool/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /var/www/traktorpool/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/traktorpool/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(Nwidart\\Modules\\Commands\\ModuleMakeCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/traktorpool/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/traktorpool/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/traktorpool/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"} 

   Nwidart\Modules\Exceptions\ModuleNotFoundException 

  Module [Test] does not exist!

  at vendor/nwidart/laravel-modules/src/FileRepository.php:366
    362▕         if ($module !== null) {
    363▕             return $module;
    364▕         }
    365▕ 
  ➜ 366▕         throw new ModuleNotFoundException("Module [{$name}] does not exist!");
    367▕     }
    368▕ 
    369▕     /**
    370▕      * Get all modules as laravel collection instance.

      +29 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

PHP version: 8.1.9
laravel/framework v9.27.0
nwidart/laravel-modules 9.0.5

Any ideas why this fails?

"Fun fact": I stepped through the process with xdebug several times. And one time it happend to work like magic. But when I retried it was broken again.

To reproduce I always deleted the newly created files in the modules directory.
Yes: we renamed the modules directory to lowercase by config.

**Comment by alissn** [comment]
Hi, @ahlvd 

if publish config file, please remove or rename config/modules.php file , and test again.

**Comment by ahlvd** [comment]
Ok, that helped. I will try to figure out which setting broke everything.
Thanks a lot, @alissn!

**Comment by ahlvd** [comment]
For everyone else struggling with this problem: It seems, that enabling the cache with `modules.cache.enabled` leads to the `module:make` command not working. Clearing the cache with `artisan cache:clear` didn't help; I tried that before.

Perhaps this could be fixed in a future release. 🙏
For now I will enable caching only for production environment.
