### ISSUE TITLE
TypeError in Builder.php when using call_user_func_array()

### ISSUE THREAD

**Issue by radiantjuan** [nWidart/laravel-modules#1820]
Ever since I did `compose update` and got the v11.0.5 version, This error shows whenever I do `php artisan module:migrate-refresh --seed`, everything is good with all other migrate command, only the one with refresh is broken

```
[2024-04-20 07:25:50] local.ERROR: call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object {"exception":"[object] (TypeError(code: 0): call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object at /var/www/manilawater/vendor/mongodb/laravel-mongodb/src/Query/Builder.php:491)
[stacktrace]
#0 /var/www/manilawater/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(242): MongoDB\\Laravel\\Query\\Builder->getFresh(Array)
#1 /var/www/manilawater/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(558): MongoDB\\Laravel\\Query\\Builder->get(Array)
#2 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3362): MongoDB\\Laravel\\Query\\Builder->aggregate('count', Array)
#3 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Migrations/Migrator.php(174): Illuminate\\Database\\Query\\Builder->count()
#4 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Commands/Database/MigrateResetCommand.php(40): Nwidart\\Modules\\Migrations\\Migrator->reset()
#5 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Commands/BaseCommand.php(60): Nwidart\\Modules\\Commands\\Database\\MigrateResetCommand->executeAction('ContentManager')
#6 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Nwidart\\Modules\\Commands\\BaseCommand->handle()
#7 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#9 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call(Array)
#12 /var/www/manilawater/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('module:migrate-...', Array, Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Commands/Database/MigrateRefreshCommand.php(29): Illuminate\\Console\\Command->call('module:migrate-...', Array)
#17 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(40): Nwidart\\Modules\\Commands\\Database\\MigrateRefreshCommand->Nwidart\\Modules\\Commands\\Database\\{closure}()
#18 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render('Refreshing Migr...', Object(Closure))
#19 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Commands/Database/MigrateRefreshCommand.php(28): Illuminate\\Console\\View\\Components\\Factory->__call('task', Array)
#20 /var/www/manilawater/vendor/nwidart/laravel-modules/src/Commands/BaseCommand.php(60): Nwidart\\Modules\\Commands\\Database\\MigrateRefreshCommand->executeAction('ContentManager')
#21 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Nwidart\\Modules\\Commands\\BaseCommand->handle()
#22 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#24 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call(Array)
#27 /var/www/manilawater/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /var/www/manilawater/vendor/symfony/console/Application.php(1049): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/manilawater/vendor/symfony/console/Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand(Object(Nwidart\\Modules\\Commands\\Database\\MigrateRefreshCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/manilawater/vendor/symfony/console/Application.php(169): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/manilawater/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/manilawater/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 

```

**Comment by dcblogdev** [comment]
can't replicate this on the latest release
