### ISSUE TITLE
Error when run `npm run dev` on Module folder

### ISSUE THREAD

**Issue by ihsaneddin** [nWidart/laravel-modules#566]
When I run `npm run dev` on module folder, it generates error like this:

`cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/jerry/Works/php.local/bitbill/node_modules/laravel-mix-merge-manifest/node_modules/laravel-mix/src/helpers.js:21
Object.defineProperty(Array.prototype, 'tap', {
       ^

TypeError: Cannot redefine property: tap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/home/jerry/Works/php.local/bitbill/node_modules/laravel-mix-merge-manifest/node_modules/laravel-mix/src/helpers.js:21:8)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jerry/Works/php.local/bitbill/node_modules/laravel-mix-merge-manifest/node_modules/laravel-mix/src/index.js:16:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jerry/.npm/_logs/2018-06-27T10_41_30_415Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
`

here is my package.json file
`
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.16.2",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.0.1",
        "jquery": "^3.1.1",
        "laravel-mix": "^2.1",
        "lodash": "^4.17.4",
        "vue": "^2.1.10"
    },
    "dependencies": {
        "bootstrap": "^4.0.0",
        "clipboard": "^2.0.0",
        "font-awesome": "^4.5.0",
        "jquery-countdown": "^2.2.0",
        "laravel-echo": "^1.3.4",
        "popper.js": "^1.14.3",
        "pusher-js": "^4.2.2"
    }
}
`

here is my main composer.json file 

`
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": {
        "coinpayments": {
            "type": "path",
            "url": "Modules/Support/Packages/*",
            "options": {
                "symlink": true
            }
        },
        "open_struct": {
            "type": "path",
            "url": "Modules/Support/Packages/*",
            "options": {
                "symlink": true
            }
        }
    },
    "require": {
        "php": ">=7.0.0",
        "acacha/stateful-eloquent": "^0.1.8",
        "ajthinking/tinx": "^2.1",
        "austinheap/laravel-database-encryption": "^0.1.1",
        "codesleeve/laravel-stapler": "dev-master",
        "efficiently/jquery-laravel": "^2.3",
        "emadadly/laravel-uuid": "^1.2",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "ihsaneddin/coinpayments": "0.0.1.1-dev",
        "ihsaneddin/open_struct": "dev-master",
        "laravel-notification-channels/webhook": "^1.2",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "5.5",
        "league/fractal": "^0.17.0",
        "nanigans/single-table-inheritance": "^0.8.2",
        "nesbot/carbon": "^1.27",
        "nwidart/laravel-modules": "^3.2",
        "predis/predis": "^1.1",
        "prettus/l5-repository": "^2.6",
        "pusher/pusher-php-server": "^3.0",
        "themsaid/laravel-mail-preview": "^2.0",
        "true/punycode": "^2.1"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": false
}

`

I don't know if this related to laravel-mix or just this repository, Could anybody give me direction, I am stuck all day

**Comment by ihsaneddin** [comment]
apprently, some default npm package laravel causing this, I still don't know which one. close this
