### ISSUE TITLE
Permission failure whenever I add my module to the application

### ISSUE THREAD

**Issue by andersonpem** [nWidart/laravel-modules#647]
Hi nwidart. Thanks for the great package.
I'm finding a serious issue here. Whenever I add my package to a Laravel project, laravel throws:

> The bootstrap/cache directory must be present and writable.

However, if I remove the module the application runs normally. I can't run artisan commands when the module is present, since Laravel does not complete the bootup process.

I can confirm the bootstrap/cache directory is writable. My user can write on it and also www-data can write on it too, since permissions were given to the group www-data to write in this directory.

Am I missing something in my module registering? Could you please analyze it?
Here is the repo:

https://gitlab.com/andersonpem/menubuilder-module

**My stack:**
- [host machine] ubuntu 18.04 LTS
- PHP (local) 7.2.11
- Docker webserver image: nginx-apline
- Docker php-fpm image: phpdockerio/php72-fpm:latest
 
- The user and groups who own all the files in the project: www-data:www-data
- bootstrap/cache have write permissions for the owner and group

**Log details:**
``` 
[2018-10-17 17:29:05] local.ERROR: The bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The bootstrap/cache directory must be present and writable. at /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:190)
[stacktrace]
#0 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(165): Illuminate\\Foundation\\ProviderRepository->writeManifest(Array)
#1 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#2 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/Module.php(251): Nwidart\\Modules\\Laravel\\Module->registerProviders()
#4 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/FileRepository.php(299): Nwidart\\Modules\\Module->register()
#5 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\FileRepository->register()
#6 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#7 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#8 /home/developer/repos/gama-portal-dep/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#9 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#10 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#15 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 23)
#17 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#18 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /home/developer/repos/gama-portal-dep/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#22 /home/developer/repos/gama-portal-dep/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"} 
```

Thank you for your time. :)

**Comment by andersonpem** [comment]
Oh by the way the repo page has some misinformation about installing the module :P my bad. It's a package still in development.

**Comment by nWidart** [comment]
Hello,

Not sure why it's not writable for you. I'll try to run your app to see.

The error is clear though.

What package is still in development?

**Comment by nWidart** [comment]
I'm indeed getting the same error with your module.

Try to see what you're writing to that folder.

**Comment by nWidart** [comment]
I can see it's the registering of the provider causing the issue. I'm not sure why only with your provider.

**Comment by nWidart** [comment]
Ok, I've found the issue 😄 You can't have the name of the module have a slash in its name. It tried to write in the `andersonpem/` directory.

**Comment by andersonpem** [comment]
Oh, I thought the name was just like the one for composer. How dumb of me. Thank you sir :)
